"""fix_slot_index_and_add_appointments

Revision ID: 3aac7806b330
Revises: d93d110f44ee
Create Date: 2026-06-11 13:11:47.497025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aac7806b330'
down_revision: Union[str, Sequence[str], None] = 'd93d110f44ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_slot_provider_start', 'appointment_slots', ['provider_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slot_provider_start', table_name='appointment_slots')
    # ### end Alembic commands ###
